# Generated by Django 5.0.7 on 2024-12-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_episode_number_series_post_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text='Schedule published date.', null=True),
        ),
    ]
